### ISSUE TITLE
Generate phaser.d.ts

### ISSUE THREAD

**Issue by vagabon** [digitsensitive/phaser3-typescript#14]
Hello, 

I want to know if your phaser.d.ts work with the v3.11 of Phaser and how did you generate it ?

Thx

**Comment by digitsensitive** [comment]
hello @vagabon 
I downloaded the [phaser.d.ts](https://github.com/photonstorm/phaser3-docs/tree/master/typescript) from the official source and only made small changes (see my game examples descriptions).

**Comment by vagabon** [comment]
Okay thx, i took your version for my game and it's working fine
