### ISSUE TITLE
"space-shooter" is not displayed 😭

### ISSUE THREAD

**Issue by ttsukasan** [digitsensitive/phaser3-typescript#284]
The game object "space shooter" is not displayed 😭😭😭

Google chrome console outputs an error

```
GET http://localhost:8080/dist/bundle.js net::ERR_ABORTED 404 (Not Found)
```

I changed npm script settings and now it shows up!

https://github.com/digitsensitive/phaser3-typescript/blob/e1f21828037aac76f5d8f8ce54e976e4c7d49e39/src/games/space-shooter/package.json#L18

```
"dev": "webpack --mode development && webpack serve --mode development"
```

Finally, thank you for making so many great games! 🥰

**Comment by digitsensitive** [comment]
@ttsukasan Still a problem? Should be fixed I think.
