### ISSUE TITLE
"endless-runner" does not start 😭

### ISSUE THREAD

**Issue by ttsukasan** [digitsensitive/phaser3-typescript#285]
"endless-runner" does not start 😭😭😭

Here is the error message I got

```
[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'publicPath'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
error Command failed with exit code 2.
```

I removed the PublicPath entry from the webpack configuration and it started.

https://github.com/digitsensitive/phaser3-typescript/blob/master/src/games/endless-runner/webpack.config.js#L25

https://github.com/digitsensitive/phaser3-typescript/blob/e1f21828037aac76f5d8f8ce54e976e4c7d49e39/src/games/endless-runner/webpack.config.js#L25

Finally, thank you for making so many great games! 🥰

**Comment by digitsensitive** [comment]
@ttsukasan Still a problem? Should be fixed I think.
