### ISSUE TITLE
"flappy-bird" title display is incorrect

### ISSUE THREAD

**Issue by ttsukasan** [digitsensitive/phaser3-typescript#286]
"Flappy Bird" title appears to show "Coin Runner"

https://github.com/digitsensitive/phaser3-typescript/blob/e1f21828037aac76f5d8f8ce54e976e4c7d49e39/src/games/flappy-bird/index.html#L3-L12

**Comment by digitsensitive** [comment]
@ttsukasan Thanks for spotting. It's fixed now.
