### ISSUE TITLE
Phaser 3 configuration structures document

### ISSUE THREAD

**Issue by Abwuds** [digitsensitive/phaser3-typescript#3]
I know this is not the right place, 
But you are the only repo where I found a correct description of the game [configuration](https://github.com/digitsensitive/phaser3-typescript/blob/master/cheatsheets/game-config.md).

Where can I find all the description of these structures for Phaser 3?
For example, what type and behavior correspond to the field "scene" in the game-configuration
and other structures?

Thank you

**Comment by digitsensitive** [comment]
hello @Abwuds 
thank you for your message. you can find all the descriptions in the [official code](https://github.com/photonstorm/phaser). Unfortunately, there is currently no other way than to go through the code yourself.

I will update my repo as quick as possible, to make Phaser 3 even easier to use.
