### ISSUE TITLE
VS Code debugging

### ISSUE THREAD

**Issue by CipSoft-Components** [digitsensitive/phaser3-typescript#30]
How can I debug the project with VS Code? When I set a breakpoint and start debugging, the breakpoint gets "Unverified breakpoint". How do I have to configure this project, to get debugging in VS Code working?
I also tried the https://github.com/TristanBonsor/phangular project, and there, the debugging works. But I want phaser with typescript without angular.

**Comment by digitsensitive** [comment]
hello @CipSoft-Components 

I have updated the `tsconfig.json` recently with the sourceMap property set to true ([see here](https://github.com/digitsensitive/phaser3-typescript/blob/9f2f46d250968e1dd1c4b987d1d6411cb7eccefd/tsconfig.json#L5)). Do you still experience the error?

**Comment by CipSoft-Components** [comment]
Thank you, with this it is working!

**Comment by digitsensitive** [comment]
Great! Closing this issue.
