### ISSUE TITLE
Webpack config for production?

### ISSUE THREAD

**Issue by KokoDoko** [digitsensitive/phaser3-typescript#32]
The current webpack configuration and examples use images that are loaded from the `src` folder, and a html file that sits in the root of the project instead of the `dist` folder.

Would it be possible to include a webpack config file that places all needed files in the `dist` folder?

Currently, running `nom run build` results in a huge `.js` file that includes all images... that can't be right?

**Comment by digitsensitive** [comment]
Hello @KokoDoko! Thank you for your message. Do you have an example github project with that configuration?

**Comment by KokoDoko** [comment]
Hi! I recently switched to [Parcel](https://parceljs.org), I find it much easier to configure than Webpack. Parcel creates a nice and tidy docs folder. You can see an example here: https://github.com/KokoDoko/ruimtegruis

If you want to use it, you just have to copy `package.json` and perhaps `tsconfig.json`. Then delete the `node_modules` folder and install it again with `npm install`. In my case it worked right away!

**Comment by philipgriffin** [comment]
@KokoDoko Parcel is decent, I still prefer webpack for now myself. You can modify the webpack config to use an extra dependency if you wanted like [CopyWebpackPlugin](https://www.npmjs.com/package/copy-webpack-plugin).

`npm i -D copy-webpack-plugin`

webpack.config.js
  ```javascript
module.exports = {
plugins: [
    new CopyWebpackPlugin([
      { from: "assets", to: "assets/" },
      { from: "index.html" }
    ])
  ],
...
}
```
Output (depending on your config)
![image](https://user-images.githubusercontent.com/17783426/77007734-a424bc00-695c-11ea-8a42-5e44ea9e8732.png)

**Comment by digitsensitive** [comment]
Closed Issue due to inactivity and no need to switch to Parcel atm.
