### ISSUE TITLE
Phaser 3.18

### ISSUE THREAD

**Issue by matiux** [digitsensitive/phaser3-typescript#35]
Is the update to version 3.18 scheduled?

**Comment by digitsensitive** [comment]
Hello @matiux 
There is no fix schedule. I wanted to update it already some time ago, but due to too many TS-Def. errors I decided against it. I will have a look at it shortly again. I keep you updated!

**Comment by digitsensitive** [comment]
@matiux This went quite fast, the repo now is up-to-date. Did not have many problems left. There is one workaround I had to do, which made it necessary to copy to original typescript definition file to my repo and make a small change (see here: https://github.com/digitsensitive/phaser3-typescript/blob/master/src/phaser-typescript-issues.md).

Have fun! :-)

**Comment by matiux** [comment]
Thanks @digitsensitive I will try asap.

I have wrap you project in a docker container.
Maybe I could get you a pull request if this feature is useful for all.
