### ISSUE TITLE
Make repository a Template Repository

### ISSUE THREAD

**Issue by atkinchris** [digitsensitive/phaser3-typescript#37]
Making this repository a "Template repository", would allow developers to use it as a base, without forking it.

![Screenshot 2019-08-02 at 08 06 02](https://user-images.githubusercontent.com/1479528/62351088-7dfcf980-b4fc-11e9-8a8d-bb7b2574722e.png)

**Comment by digitsensitive** [comment]
Hello @atkinchris! Thank you for your input. I think this repository has too many other stuff, which is not needed for a project and therefor does not classify as a template repository.

Would it be helpful if I create a new repository with only a boilerplate?

**Comment by atkinchris** [comment]
>I think this repository has too many other stuff, which is not needed for a project and therefore does not classify as a template repository.

That makes sense!

>Would it be helpful if I create a new repository with only a boilerplate?

I think another repository would risk one of the two becoming stale (and adds more maintenance) - your "Getting started" section covers it nicely.
