### ISSUE TITLE
 Why are not you deploying type definition?

### ISSUE THREAD

**Issue by cicada0014** [digitsensitive/phaser3-typescript#4]
Thank you for your efforts.

I am using your phaser.d.ts well.

I have one question. 

 Why are not you deploying type definition?.

[type definition](https://github.com/DefinitelyTyped/DefinitelyTyped)

I want you to merge your code to type definition repository.

So, many people will be able to use your type definition. 

just command 

```bash
 npm install @types/phaser 
```

**Comment by digitsensitive** [comment]
Currently I do not have the time to work on the phaser.d.ts.

I do not want to create an own type definition file. But if I encounter an error while developing my projects, I update the corresponding code myself and report it in the official github repository. As soon as they fix it, I will update the phaser.d.ts again.
