### ISSUE TITLE
Most games are not compiling

### ISSUE THREAD

**Issue by scottschafer** [digitsensitive/phaser3-typescript#56]
If I change the webpack.config.js to point to various games, I run into this compile issue:
https://github.com/photonstorm/phaser3-docs/issues/24

For example,
  entry: './src/games/space-invaders/game.ts',

ERROR in /Users/sschafer/personal/projects/phaser3-typescript/src/games/asteroid/objects/asteroid.ts
[tsl] ERROR in /Users/sschafer/personal/projects/phaser3-typescript/src/games/asteroid/objects/asteroid.ts(37,15)
      TS2339: Property 'allowGravity' does not exist on type 'Body | StaticBody | BodyType'.
  Property 'allowGravity' does not exist on type 'BodyType'.

What's the best way to resolve this?

**Comment by digitsensitive** [comment]
@scottschafer Hello! The problem should be solved now. A lot of it was out of date. I have refactored every game. Every game is now an independent project.

**Comment by scottschafer** [comment]
Thank you Eric! Much appreciated
