### ISSUE TITLE
Webpack template not functioning correctly.

### ISSUE THREAD

**Issue by nobody5050** [digitsensitive/phaser3-typescript#73]
I’m using a modified version of [github pages deploy](https://github.com/JamesIves/github-pages-deploy-action) to build and run my game on github pages branch.

running
```sh
yarn install
yarn dev
```

results in the bundle.js being committed to the gh-pages branch, but nothing else. How can I fix this?

**Comment by digitsensitive** [comment]
I do not know about github pages deploy. Is it still a problem?
